### ISSUE TITLE
Bug when updating skins

### ISSUE THREAD

**Issue by Jeimy041** [namazso/nSkinz#101]
![screenshot_1](https://user-images.githubusercontent.com/38838740/44982884-9b85b400-af77-11e8-937e-3e471bf98995.png)

So as you can see the gloves are somehow glitched but this only happens if I change the skin, this happens with all the weapon models and knife models. As a temporary fix for me after tabbing out of the game and tabbing in again seems to fix it.
Maybe is just my problem because everything was working fine before so if noone has this issue too I will try to fix it by myself.
Thank you all!!!!

**Comment by wardinh0** [comment]
With skins, if you drop them and pick them up it fixes as well, you don't need to Alt + Tab, but for knives and gloves you still need to

**Comment by namazso** [comment]
If the suggested way works that means forceupdate is now sensitive of when its done. Currently setting is done in render thread because it hasn't caused problems so far. Commands are always queued and executed in game thread, so thay would explain why it fixes the problem.

**Comment by MagicTripz** [comment]
I compiled it yesterday and i realized the way forceupdate is called is really fucking up some parts of the game, atleast for me i'd go with the safe way (especially for most ac's) aka record x;stop. Pretty easy to implement just delete from the menu the forceupdate call, implement if not already there engine->Clientcmdunrestricted , and just on let your cheat type "record x;stop" every time the update button gets pressed. If you are really down to change things you could also implement instant kit updates(https://www.unknowncheats.me/forum/counterstrike-global-offensive/225472-instant-weapon-paintkit-update-fullupdate.html)

**Comment by M1XT3NZ** [comment]
as of #106 this is now fixed

**Comment by fostersmiles** [comment]
still not fixed mate, im running at the newest version and it is still doing the same thing, but alt+tab fixes it and the record x:stop too

**Comment by M1XT3NZ** [comment]
It’s actually weird I do not have this problem at all.
